language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
    - "python setup.py build install"
    - "pip install pylint ddt"
# command to run tests
script: ./run_tests.sh

